[package]
name = "wav-files-validate"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
hound = "3.5.1"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.23.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
